### ISSUE TITLE
GUI钱包不能查看最新的交易记录了

### ISSUE THREAD

**Issue by netmebtc** [bigbangcore/GUI-Client#2]
GUI1.0钱包，能够同步100%，余额也会变化，但是交易记录不会刷新了，无法查看最近的交易记录了。

**Comment by DrakeXiang** [comment]
更新到1.1.0试试看呢？

**Comment by netmebtc** [comment]
更新到1.1.0版本 还是看不到最新的交易记录。

**Comment by netmebtc** [comment]
目前看到的最后的交易记录是   2020-01-14 09:30 的，从这个时间到现在的交易记录全部都看不到

**Comment by DrakeXiang** [comment]
在web版的区块链浏览器上可以看到吗？另外可以尝试使用cli钱包看看，现在相关的同事都放假了，可能问题得年后才能解决了~:joy:

**Comment by netmebtc** [comment]
CLI钱包能正常看到的。 GUI钱包的总的余额也对，就是最近的交易记录不显示了。

**Comment by netmebtc** [comment]
还在放假？

**Comment by DrakeXiang** [comment]
抱歉，前几天同事拿了个账号测了一下交易显示正常，忘了回复了

**Comment by netmebtc** [comment]
我的钱包有10个接收地址。你们多搞点接收地址 然后我的地址从12月2日就开始有交易记录，目前只显示到1月12日的

**Comment by netmebtc** [comment]
对了，交易记录的页数总共50页，估计就是这个问题，你们是不是只显示50页的，超过了50页的交易记录就不再显示了

**Comment by DrakeXiang** [comment]
> 对了，交易记录的页数总共50页，估计就是这个问题，你们是不是只显示50页的，超过了50页的交易记录就不再显示了

看了下确实是这个原因😂，感谢。下个版本会修复

**Comment by netmebtc** [comment]
下一個版本需要等多久？

**Comment by DrakeXiang** [comment]
> 下一個版本需要等多久？

发[新版](https://github.com/bigbangcore/GUI-Client/releases/tag/v1.1.1)了，试试看

**Comment by netmebtc** [comment]
OK. 新版本可以显示最新的交易记录了。
